# Requires that the survey results are loaded into the following data frame
# mysurveys
# Generates a matrix with matrix sums for all checkbox categories (rows) for all questions (cols)

myanswersums = colSums(
  mysurveys[,c(
    "asctr_1_1_locus_options___1",
    "asctr_1_1_locus_options___2",
    "asctr_1_1_locus_options___3",
    "asctr_1_1_locus_options___4",
    "asctr_1_1_sust_options___1",
    "asctr_1_1_sust_options___2",
    "asctr_1_1_sust_options___3",
    "asctr_1_1_sust_options___4",
    
    "asctr_2_1_locus_options___1",
    "asctr_2_1_locus_options___2",
    "asctr_2_1_locus_options___3",
    "asctr_2_1_locus_options___4",
    "asctr_2_1_sust_options___1",
    "asctr_2_1_sust_options___2",
    "asctr_2_1_sust_options___3",
    "asctr_2_1_sust_options___4",
    
    "asctr_3_1_locus_options___1",
    "asctr_3_1_locus_options___2",
    "asctr_3_1_locus_options___3",
    "asctr_3_1_locus_options___4",
    "asctr_3_1_sust_options___1",
    "asctr_3_1_sust_options___2",
    "asctr_3_1_sust_options___3",
    "asctr_3_1_sust_options___4",
    
    "asctr_4_1_locus_options___1",
    "asctr_4_1_locus_options___2",
    "asctr_4_1_locus_options___3",
    "asctr_4_1_locus_options___4",
    "asctr_4_1_sust_options___1",
    "asctr_4_1_sust_options___2",
    "asctr_4_1_sust_options___3",
    "asctr_4_1_sust_options___4",
    
    "asctr_5_1_locus_options___1",
    "asctr_5_1_locus_options___2",
    "asctr_5_1_locus_options___3",
    "asctr_5_1_locus_options___4",
    "asctr_5_1_sust_options___1",
    "asctr_5_1_sust_options___2",
    "asctr_5_1_sust_options___3",
    "asctr_5_1_sust_options___4",
    
    "asctr_6_1_locus_options___1",
    "asctr_6_1_locus_options___2",
    "asctr_6_1_locus_options___3",
    "asctr_6_1_locus_options___4",
    "asctr_6_1_sust_options___1",
    "asctr_6_1_sust_options___2",
    "asctr_6_1_sust_options___3",
    "asctr_6_1_sust_options___4",
    
    "asctr_7_1_locus_options___1",
    "asctr_7_1_locus_options___2",
    "asctr_7_1_locus_options___3",
    "asctr_7_1_locus_options___4",
    "asctr_7_1_sust_options___1",
    "asctr_7_1_sust_options___2",
    "asctr_7_1_sust_options___3",
    "asctr_7_1_sust_options___4",
    
    "asctr_8_1_locus_options___1",
    "asctr_8_1_locus_options___2",
    "asctr_8_1_locus_options___3",
    "asctr_8_1_locus_options___4",
    "asctr_8_1_sust_options___1",
    "asctr_8_1_sust_options___2",
    "asctr_8_1_sust_options___3",
    "asctr_8_1_sust_options___4",
    
    "asctr_9_1_locus_options___1",
    "asctr_9_1_locus_options___2",
    "asctr_9_1_locus_options___3",
    "asctr_9_1_locus_options___4",
    "asctr_9_1_sust_options___1",
    "asctr_9_1_sust_options___2",
    "asctr_9_1_sust_options___3",
    "asctr_9_1_sust_options___4",
    
    "asctr_10_1_locus_options___1",
    "asctr_10_1_locus_options___2",
    "asctr_10_1_locus_options___3",
    "asctr_10_1_locus_options___4",
    "asctr_10_1_sust_options___1",
    "asctr_10_1_sust_options___2",
    "asctr_10_1_sust_options___3",
    "asctr_10_1_sust_options___4",
    
    "rc_1_1_locus_options___1",
    "rc_1_1_locus_options___2",
    "rc_1_1_locus_options___3",
    "rc_1_1_locus_options___4",
    "rc_1_1_sust_options___1",
    "rc_1_1_sust_options___2",
    "rc_1_1_sust_options___3",
    "rc_1_1_sust_options___4",
    
    "ci_1_1_locus_options___1",
    "ci_1_1_locus_options___2",
    "ci_1_1_locus_options___3",
    "ci_1_1_locus_options___4",
    "ci_1_1_sust_options___1",
    "ci_1_1_sust_options___2",
    "ci_1_1_sust_options___3",
    "ci_1_1_sust_options___4",
    
    "ci_2_1_locus_options___1",
    "ci_2_1_locus_options___2",
    "ci_2_1_locus_options___3",
    "ci_2_1_locus_options___4",
    "ci_2_1_sust_options___1",
    "ci_2_1_sust_options___2",
    "ci_2_1_sust_options___3",
    "ci_2_1_sust_options___4",
    
    "og_1_1_locus_options___1",
    "og_1_1_locus_options___2",
    "og_1_1_locus_options___3",
    "og_1_1_locus_options___4",
    "og_1_1_sust_options___1",
    "og_1_1_sust_options___2",
    "og_1_1_sust_options___3",
    "og_1_1_sust_options___4",
    
    "ts_1_1_locus_options___1",
    "ts_1_1_locus_options___2",
    "ts_1_1_locus_options___3",
    "ts_1_1_locus_options___4",
    "ts_1_1_sust_options___1",
    "ts_1_1_sust_options___2",
    "ts_1_1_sust_options___3",
    "ts_1_1_sust_options___4",
    
    "mri_1_1_locus_options___1",
    "mri_1_1_locus_options___2",
    "mri_1_1_locus_options___3",
    "mri_1_1_locus_options___4",
    "mri_1_1_sust_options___1",
    "mri_1_1_sust_options___2",
    "mri_1_1_sust_options___3",
    "mri_1_1_sust_options___4"
    
  )]
)

myanswersumsmatrix = matrix( myanswersums, nrow = 8, ncol = 16 )
myanswersumsdf = as.data.frame(myanswersumsmatrix)
colnames(myanswersumsdf)=c(
  "Research/Regulatory Compliance" , 
  "Service Request / Fulfillment" , 
  "Program Evaluation" , 
  "Grants and Contracts Systems", 
  "CTMS Components", 
  "Electronic Data Capture", 
  "Biobanking Systems", 
  "Data Repositories and EHR Data", 
  "Clinical Medical Information Systems (EHR Systems Research Interface)",
  "Communication",
  "Extramural data collaborations",
  "Security",
  "IT Infrastructure",
  "Governance",
  "Education",
  "Informatics innovation"
  )
row.names(myanswersumsdf)=c(
  "Informatics",
  "Research Office",
  "CIO/IT",
  "Other locus",
  "Institutional",
  "Fee for Service / Charge Back",
  "Grants",
  "Other source"
)
write.csv(myanswersumsdf, file='output/quantitative_sums.csv',
          row.names = TRUE, col.names = TRUE, sep = ",")